### ISSUE TITLE
Saving input value

### ISSUE THREAD

**Issue by superjoeman3** [superjoeman3/CarboNation#1]
I can't figure out a way to save the input value (or MPG) in our carbon emissions equation. Right now, the equation doesn't take MPG into consideration.

**Comment by dgoode7** [comment]
Damn

**Comment by jlyon** [comment]
http://ionicframework.com/docs/guide/building.html

**Comment by jlyon** [comment]
https://github.com/superjoeman3/CarboNation/commit/aac73507c0fb0fc6b87ff0e4819721d6bf3cbac6
