### ISSUE TITLE
Parse

### ISSUE THREAD

**Issue by superjoeman3** [superjoeman3/CarboNation#4]
The graph we had already created on parse is no longer there. Also, the data from the website is no longer being pushed to parse. Jeff, could you send the link of the website guide we were following?

**Comment by jlyon** [comment]
sorry for the slow reply. ill try to dig it up. Could you send the parse u/p?  I don't think we ever set up a graph with parse, did we?

Do you want to try to get together to work on this this weekend?

**Comment by jlyon** [comment]
here's the tutorial we were using: http://www.htmlxprs.com/post/12/tutorial-on-using-parse-rest-api-and-ionic-framework-together

**Comment by superjoeman3** [comment]
Hey could we meet up this weekend to work on the parse component?

**Comment by jlyon** [comment]
Yeah, tomorrow afternoon?

**Comment by superjoeman3** [comment]
I think I got it working again actually

**Comment by superjoeman3** [comment]
But I haven't finished the parse tutorial completely, so it might help if we did meet

**Comment by jlyon** [comment]
3pm tomorrow?
